### ISSUE TITLE
unexpected keyword argument 'sla'

### ISSUE THREAD

**Issue by battlemidget** [juju-solutions/matrix#124]
Attempting to run 

```
juju matrix -p spells/kubernetes-core -l DEBUG
```

Results in the following error:

```
websockets.protocol:528:read_frame: client << Frame(fin=True, opcode=1, data=b'{"request-id":8,"response":{"name":"matrix-noble-mink","uuid":"c92b7150-e6e4-4a09-8e0b-e8c00481e0d1","controller-uuid":"adf2cada-ea18-42e3-819b-a99567bc8e31","provider-type":"lxd","default-series":"xenial","cloud-tag":"cloud-localhost","cloud-region":"localhost","cloud-credential-tag":"cloudcred-localhost_admin_localhost","owner-tag":"user-admin","life":"alive","status":{"status":"available","info":"","since":"2017-04-07T23:45:09.286253722Z"},"users":[{"user":"admin","display-name":"admin","last-connection":null,"access":"admin"}],"machines":null,"sla":{"level":"unsupported","owner":""}}}\n')
matrix:382:run: Error adding model: __init__() got an unexpected keyword argument 'sla'
matrix:388:run: end_to_end Complete False {}
juju.controller:53:disconnect: Closing controller connection
websockets.protocol:544:write_frame: client >> Frame(fin=True, opcode=8, data=b'\x03\xe8')
websockets.protocol:528:read_frame: client << Frame(fin=True, opcode=8, data=b'\x03\xe8')
```

This is using Juju 2.2 from their develop branch (installed with `sudo snap install conjure-up --edge --classic`)

**Comment by petevg** [comment]
@battlemidget This is unfortunately expected for now. matrix only works with juju 2.1, until I finish up the work outlined here: https://github.com/juju/python-libjuju/issues/49

ETA for that work is still the end of this week -- I'll keep people updated if that slips ...

**Comment by petevg** [comment]
@battlemidget It looks like I'm not going to have the versioning support done by the end of this week. :-( 

The latest is that I may have run into a bug in juju (https://bugs.launchpad.net/juju/+bug/1682925), and need to write a workaround.

I'll keep you posted on progress.

**Comment by petevg** [comment]
I added versioning support to python-libjuju, and updated matrix with the latest code.

Per IRC convo w/ @battlemidget, this one is fixed.
